name: Update M3U8 Links

on:
  schedule:
    - cron: "*/5 * * * *"   # 5 dakikada 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install requests

      - name: Run script
        env:
          SRC_1: bo.xxx.workers.dev
          SRC_2: f6e33e69e0fdec0a7780e174f3c8b2c2
          VIDEO_ID: "777"
          BASE_URL: https://site.com
        run: |
          python links.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add links.txt
          git commit -m "update m3u8 links" || echo "no changes"
          git push
